Update README
mlrun/genai-factory pull request #31
Opened 2024-09-26 20:57 UTC by nschenone

Added more information on overview, architecture, usage, and configuration in README

2024-10-01 14:35 UTC, guy1992l requested changes
Thank you so much Nick, you are the best!

The env vars were renamed (and if not they should be...) so please take a look. If they didn't renamed then I'll merge and rename them on another PR.

2024-10-01 14:35 UTC, guy1992l commented on README.md
> +    MLRUN_GENAI_LOCAL_CHROMA=/tmp/chromadb  # Path to local Chroma database (if applicable)
I think the env vars prefixes were renamed from `MLRUN_GENAI` to `GENAI_FACTORY`

2024-10-01 16:42 UTC, nschenone commented
@guy1992l Looks like it wasn't changed yet, but I updated the env var in the code and the docs. Should be good to go

2024-10-14 16:12 UTC, guy1992l approved these changes

2024-10-14 16:12 UTC, merged